name: Helm Chart OCI Publish

on:
  push:
    branches:
      - main # Or your desired branch
  workflow_dispatch: # Allows manual triggering

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4 # Use the latest version

      - name: Package Helm chart
        run: |
          HELM_CHART_PATH="./charts/nginx" # Adjust to your chart's path
          HELM_CHART_NAME=$(basename $HELM_CHART_PATH)
          HELM_CHART_VERSION=latest
          helm package $HELM_CHART_PATH --version $HELM_CHART_VERSION

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Push Helm chart to GHCR
        run: |
          HELM_CHART_PATH="./charts/nginx" # Adjust to your chart's path
          HELM_CHART_NAME=$(basename $HELM_CHART_PATH)
          HELM_CHART_VERSION=$(helm inspect chart $HELM_CHART_PATH | grep 'version:' | awk '{print $2}')
          helm push ${HELM_CHART_NAME}-${HELM_CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
